#!/bin/sh

mount -t proc proc /proc
mount -t devpts devpts /dev/pts

# Enable networking
ifconfig eth0 up
udhcpc eth0 -f -q -s /bin/udhcp-script

# Inform the tester that we've booted
sleep 1s
echo "[cs194-24] init running"
ash

# Force a power down
poweroff -f
